/* Generated By:JavaCC: Do not edit this line. FreshMeatTreeConstants.java Version 5.0 */
package parser;

public interface FreshMeatTreeConstants
{
  public int JJTSTART = 0;
  public int JJTBLOCK = 1;
  public int JJTCOMMAND = 2;
  public int JJTVARIABLEASSIGNMENT = 3;
  public int JJTVARIABLEINICIALIZATION = 4;
  public int JJTIF = 5;
  public int JJTFORTO = 6;
  public int JJTWHILE = 7;
  public int JJTLOGICEXPRESSION = 8;
  public int JJTMATHEXPRESSION = 9;
  public int JJTEXPRESSIONARGUMENTS = 10;
  public int JJTMATHOPERATOR = 11;
  public int JJTLOGICOPERATOR = 12;
  public int JJTUSINGDECLARATION = 13;
  public int JJTVARIABLEDECLARATION = 14;
  public int JJTDATATYPE = 15;
  public int JJTIDLIST = 16;


  public String[] jjtNodeName = {
    "start",
    "Block",
    "Command",
    "VariableAssignment",
    "VariableInicialization",
    "If",
    "ForTo",
    "While",
    "LogicExpression",
    "MathExpression",
    "ExpressionArguments",
    "MathOperator",
    "LogicOperator",
    "UsingDeclaration",
    "VariableDeclaration",
    "DataType",
    "IDList",
  };
}
/* JavaCC - OriginalChecksum=c6311dac7bab299ec7300e4b707fcf9b (do not edit this line) */
