/* Generated By:JavaCC: Do not edit this line. FreshMeatTreeConstants.java Version 5.0 */
package parser;

public interface FreshMeatTreeConstants
{
  public int JJTSTART = 0;
  public int JJTBLOCK = 1;
  public int JJTCOMMAND = 2;
  public int JJTVARIABLEASSIGNMENT = 3;
  public int JJTVARIABLEINIT = 4;
  public int JJTY = 5;
  public int JJTW = 6;
  public int JJTDOMATH = 7;
  public int JJTIF = 8;
  public int JJTFORTO = 9;
  public int JJTWHILE = 10;
  public int JJTLOGICEXPRESSION = 11;
  public int JJTEXPRESSIONARGUMENTS = 12;
  public int JJTMATHOPERATOR = 13;
  public int JJTLOGICOPERATOR = 14;
  public int JJTUSINGDECLARATION = 15;
  public int JJTVARIABLEDECLARATION = 16;
  public int JJTDATATYPE = 17;
  public int JJTIDLIST = 18;
  public int JJTSTARTSCRIPT = 19;
  public int JJTDOUBLEPOINTS = 20;
  public int JJTID = 21;
  public int JJTLBRACE = 22;
  public int JJTRBRACE = 23;
  public int JJTSEMICOLON = 24;
  public int JJTASSIGN = 25;
  public int JJTNUMBER = 26;
  public int JJTSTRINGDELIMIT = 27;
  public int JJTTHEN = 28;
  public int JJTELSE = 29;
  public int JJTFOR = 30;
  public int JJTTO = 31;
  public int JJTSUM = 32;
  public int JJTMINUS = 33;
  public int JJTPLUS = 34;
  public int JJTDIVIDE = 35;
  public int JJTGREATER = 36;
  public int JJTLESS = 37;
  public int JJTGREATEREQUAL = 38;
  public int JJTLESSEQUAL = 39;
  public int JJTDIFFERENCE = 40;
  public int JJTEQUAL = 41;
  public int JJTUSING = 42;
  public int JJTINTEGERTYPE = 43;
  public int JJTSTRINGTYPE = 44;
  public int JJTBOOLTYPE = 45;
  public int JJTCOMMA = 46;


  public String[] jjtNodeName = {
    "start",
    "Block",
    "Command",
    "VariableAssignment",
    "VariableInit",
    "Y",
    "W",
    "DoMath",
    "If",
    "ForTo",
    "While",
    "LogicExpression",
    "ExpressionArguments",
    "MathOperator",
    "LogicOperator",
    "UsingDeclaration",
    "VariableDeclaration",
    "DataType",
    "IDList",
    "StartScript",
    "DoublePoints",
    "Id",
    "LBrace",
    "RBrace",
    "SemiColon",
    "Assign",
    "Number",
    "StringDelimit",
    "Then",
    "Else",
    "FOR",
    "To",
    "Sum",
    "Minus",
    "Plus",
    "Divide",
    "Greater",
    "Less",
    "GreaterEqual",
    "LessEqual",
    "Difference",
    "Equal",
    "Using",
    "IntegerType",
    "StringType",
    "BoolType",
    "Comma",
  };
}
/* JavaCC - OriginalChecksum=2c703057c61e371516abbcd41550ebdd (do not edit this line) */
