/* Generated By:JavaCC: Do not edit this line. FreshMeatTreeConstants.java Version 5.0 */
package parser;

public interface FreshMeatTreeConstants
{
  public int JJTSTART = 0;
  public int JJTBLOCK = 1;
  public int JJTCOMMAND = 2;
  public int JJTASSIGNMENT = 3;
  public int JJTINICIALIZATION = 4;
  public int JJTFORTO = 5;
  public int JJTWHILE = 6;
  public int JJTLOGICEXPRESSION = 7;
  public int JJTMATHEXPRESSION = 8;
  public int JJTEXPRESSIONARGUMENTS = 9;
  public int JJTMATHOPERATOR = 10;
  public int JJTLOGICOPERATOR = 11;
  public int JJTUSINGDECLARATION = 12;
  public int JJTVARIABLEDECLARATION = 13;
  public int JJTDATATYPE = 14;
  public int JJTIDLIST = 15;


  public String[] jjtNodeName = {
    "start",
    "Block",
    "Command",
    "Assignment",
    "Inicialization",
    "ForTo",
    "While",
    "LogicExpression",
    "MathExpression",
    "ExpressionArguments",
    "MathOperator",
    "LogicOperator",
    "UsingDeclaration",
    "VariableDeclaration",
    "DataType",
    "IDList",
  };
}
/* JavaCC - OriginalChecksum=b83fb779ca1cbbf7733263cc8fa3a0dc (do not edit this line) */
