/* Generated By:JavaCC: Do not edit this line. FreshMeatConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FreshMeatConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STARTSCRIPT = 5;
  /** RegularExpression Id. */
  int DOUBLEPOINTS = 6;
  /** RegularExpression Id. */
  int SEMICOLON = 7;
  /** RegularExpression Id. */
  int OPENBLOCK = 8;
  /** RegularExpression Id. */
  int CLOSEBLOCK = 9;
  /** RegularExpression Id. */
  int HASHTAG = 10;
  /** RegularExpression Id. */
  int USING = 11;
  /** RegularExpression Id. */
  int INTEGERTYPE = 12;
  /** RegularExpression Id. */
  int STRINGTYPE = 13;
  /** RegularExpression Id. */
  int BOOLTYPE = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int TO = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;
  /** RegularExpression Id. */
  int DECIMAL = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int ID = 23;
  /** RegularExpression Id. */
  int LETTER = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Start\"",
    "\":\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"#\"",
    "\"using\"",
    "\"int\"",
    "\"string\"",
    "\"bool\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"for\"",
    "\"to\"",
    "<NUMBER>",
    "<DECIMAL>",
    "<DIGIT>",
    "<ID>",
    "<LETTER>",
  };

}
